name: Heroku Awake Dev

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://zawislak-dev.herokuapp.com/" 
0 comments on commit 1a2ce64
